### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by jqnatividad**
Added TODOs for Adam and Joel before publishing to extensions.ckan.org

### CODE REVIEW

**Comment by ajb** [comment]
Just added our content to the README.

**Comment by ajb** [comment]
Opened https://github.com/ckan/extensions.ckan.org/issues/91

**Comment by jqnatividad** [comment]
Hi @ajb, 
Just qualified the screenshots so they show up on extensions.ckan.org.
Thanks!

**Comment by ajb** [comment]
Thank you!

**Pull request merged**
